[workspace]
resolver = "3"
members = ["bhwi-ffi", "bindgen"]

[workspace.package]
authors = ["Edouard Paris <m@edouard.paris>", "Trevor Arjeski <tmarjeski@gmail.com>"]
license-file = "LICENSE"

[workspace.dependencies]
bhwi = { git = "https://github.com/trevarj/bhwi", rev = "baa7111d6fb76cc0da02c907ddbb75856e4aac8c", default-features = false }
bhwi-async = { git = "https://github.com/trevarj/bhwi", rev = "baa7111d6fb76cc0da02c907ddbb75856e4aac8c" }
async-trait = "0.1"
futures = "0.3"
hex = "0.4.3"
rand_core = "0.6.4"
thiserror = "1"
uniffi = "0.32.0"

