[workspace]
resolver = "3"
members = ["bhwi-ffi", "bindgen"]

[workspace.package]
authors = ["Edouard Paris <m@edouard.paris>", "Trevor Arjeski <tmarjeski@gmail.com>"]
license-file = "LICENSE"

[workspace.dependencies]
bhwi = { git = "https://github.com/wizardsardine/bhwi", rev = "580350d258651d5329b8ef5fa1dfa9aa42a8ccb9", default-features = false }
bhwi-async = { git = "https://github.com/wizardsardine/bhwi", rev = "580350d258651d5329b8ef5fa1dfa9aa42a8ccb9" }
async-trait = "0.1"
futures = "0.3"
hex = "0.4.3"
rand_core = "0.6.4"
thiserror = "1"
uniffi = "0.32.0"
